//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResxHelperGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Localization;

public static class CultureHelper
{
    public static readonly string[] ApplicationCultures
        = new string[]
        {
            "en-US",
            "af-ZA",
            "ar-SA",
            "be-BY",
            "bn-BD",
            "ca-ES",
            "cs-CZ",
            "da-DK",
            "de-DE",
            "el-GR",
            "en-GB",
            "es-AR",
            "es-ES",
            "fa-IR",
            "fi-FI",
            "fr-FR",
            "he-IL",
            "hi-IN",
            "hu-HU",
            "id-ID",
            "is-IS",
            "it-IT",
            "ja-JP",
            "ka-GE",
            "kn-IN",
            "ko-KR",
            "kw-GB",
            "nb",
            "nl-NL",
            "pl-PL",
            "pt-BR",
            "pt-PT",
            "ro-RO",
            "ru-RU",
            "sr-SP",
            "sv-SE",
            "ta-IN",
            "te-IN",
            "tr-TR",
            "uk-UA",
            "vi-VN",
            "zh-Hans",
            "zh-Hant",
        };
}